author:     Multiple Authors
license:    Apache 2
copyright:  2012 by Dell, Inc
date:       June 1, 2012
format:     markdown
    
crowbar+book-userguide:
  crowbar+ui-utilities:
    logging+utils-export-logging:
      url:    '/utils/list'

crowbar+book-barclamps:
  logging+logging
                
crowbar+book-licenses:
  loggin+logging-licenses
