author:     Multiple Authors
license:    Apache 2
copyright:  2012 by Dell, Inc
date:       June 1, 2012
format:     markdown
    
crowbar+book-userguide:
  crowbar+ui-utilities:
    logging+utils-export-logging:
      url:    '/utils/list'

crowbar+book-barclamps:
  crowbar+barclamp-info-meta:
    - logging+barclamp-info
    
crowbar+book-licenses:
  crowbar+licenses-crowbar-meta:
    logging+licenses